import Banner from '@/components/Banner'
import Header from '@/components/Header'
import MediumCard from '@/components/MediumCard';
import SmallCard from '@/components/SmallCard';
import Head from 'next/head'

export default function Home({ exploreData, cardsData }) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header /> 
      <Banner />

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>

          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {exploreData?.map(({ img, location, distance }) => (
              <SmallCard 
                key={img}
                img={img}
                location={location}
                distance={distance}
              /> 
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>

          {cardsData?.map(({ img, title }) => {
            <MediumCard
              key={img}
              img={img}
              title={title}
            />
          })}
        </section>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch('https://links.papareact.com/pyp').
  then(
    (res) => res.json()
  );

  const cardsData = await fetch('https://links.papareact.com/zp1').
  then(
    (res) => res.json()
  )


  return {
    props: {
      exploreData,
      cardsData
    }
  }
}
